<!--#include file="../inc/data.asp"-->                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
<%                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	dim objXmlDoc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	dim strHTML  , strSQL, objRSAprovid , straprovid                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	'Criação dos objetos                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
	set objXmlDoc = server.CreateObject("Microsoft.XMLDOM")                                                                                                                                                                                                                                                                                                                                                                                                                                               
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	'Atribuição de valores para as variáveis 	                                                                                                                                                                                                                                                                                                                                                                                                                                                            
	objXmlDoc.load(Request)                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
	set aprovid	= objXmlDoc.selectSingleNode("//aprovid")                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	straprovid = aprovid.Text     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
	strSQL  = "CLA_sp_sel_Aprovisionador " & straprovid                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
	set objRSAprovid = db.execute(strSQL)                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
  strHTML = ""                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  	if (objRSAprovid("Acao")="ATV") then                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  		If not isnull(objRSAprovid("Sol_ID")) then                                                                                                                                                                                                                                                                                                                                                                                                                                                        
  			strHTML = objRSAprovid("Sol_ID") & objRSAprovid("Acl_IDAcessoLogico")'"Solicitação já criada. \n - Número da Solicitação gerada: " & objRSAprovid("Sol_ID") & " \n - Número do ID-Lógico gerado:" & objRSAprovid("Acl_IDAcessoLogico")                                                                                                                                                                                                                                                                                                                                                                                                                                
  		end if                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  	elseif (objRSAprovid("Acao")="ALT") then                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  		if (left(objRSAprovid("Acl_IDAcessoLogico"),3)="677") then                                                                                                                                                                                                                                                                                                                                                                                                                                        
  		  strHTML = objRSAprovid("Sol_ID") & objRSAprovid("Acl_IDAcessoLogico")'"Solicitação já criada. \n - Número da Solicitação gerada: " & objRSAprovid("Sol_ID") & " \n - Número do ID-Lógico gerado:" & objRSAprovid("Acl_IDAcessoLogico")                                                                                                                                                                                                                                                                                                                                                                                                                               
  		end if                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  	end if                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	set objRSAprovid = nothing                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
	Response.ContentType = "text/HTML;charset=ISO-8859-1"                                                                                                                                                                                                                                                                                                                                                                                                                                                 
	Response.Write (strHTML)                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
%>