'Recebe o cep e o estado para validar. Retorna TRUE se o CEP pertencer ao estado.
Function estadocep(CepConsulta,estadovalida)
  estadocep = FALSE
  'msgbox("CEP: " & CepConsulta)
  'msgbox("UF: " & estadovalida)
  'Recebe os primeiros dois dígitos do cep que foi consultado:
  vb_CepConsulta = mid(CepConsulta,1,2)
  'msgbox("CEP a ser consultado: " & vb_CepConsulta)
  'Identifica o(s) estado(s) de acordo com a região e sub-região:
  select case vb_CepConsulta 
    Case "01" VB_UF = "SP"
    Case "02" VB_UF = "SP"
    Case "03" VB_UF = "SP"
    Case "04" VB_UF = "SP"
    Case "05" VB_UF = "SP"
    Case "06" VB_UF = "SP"
    Case "07" VB_UF = "SP"
    Case "08" VB_UF = "SP"
    Case "09" VB_UF = "SP"
    Case "10" VB_UF = "SP"
    Case "11" VB_UF = "SP"
    Case "12" VB_UF = "SP"
    Case "13" VB_UF = "SP"
    Case "14" VB_UF = "SP"
    Case "15" VB_UF = "SP"
    Case "16" VB_UF = "SP"
    Case "17" VB_UF = "SP"
    Case "18" VB_UF = "SP"
    Case "19" VB_UF = "SP"
    Case "20" VB_UF = "RJ"
    Case "21" VB_UF = "RJ"
    Case "22" VB_UF = "RJ"
    Case "23" VB_UF = "RJ"
    Case "24" VB_UF = "RJ"
    Case "25" VB_UF = "RJ"
    Case "26" VB_UF = "RJ"
    Case "27" VB_UF = "RJ"
    Case "28" VB_UF = "RJ"
    Case "29" VB_UF = "ES"
    Case "30" VB_UF = "MG"
    Case "31" VB_UF = "MG"
    Case "32" VB_UF = "MG"
    Case "33" VB_UF = "MG"
    Case "34" VB_UF = "MG"
    Case "35" VB_UF = "MG"
    Case "36" VB_UF = "MG"
    Case "37" VB_UF = "MG"
    Case "38" VB_UF = "MG"
    Case "39" VB_UF = "MG"
    Case "40" VB_UF = "BA"
    Case "41" VB_UF = "BA"
    Case "42" VB_UF = "BA"
    Case "43" VB_UF = "BA"
    Case "44" VB_UF = "BA"
    Case "45" VB_UF = "BA"
    Case "46" VB_UF = "BA"
    Case "47" VB_UF = "BA"
    Case "48" VB_UF = "BA"
    Case "49" VB_UF = "SE"
    Case "50" VB_UF = "PE"
    Case "51" VB_UF = "PE"
    Case "52" VB_UF = "PE"
    Case "53" VB_UF = "PE"
    Case "54" VB_UF = "PE"
    Case "55" VB_UF = "PE"
    Case "56" VB_UF = "PE"
    Case "57" VB_UF = "AL"
    Case "58" VB_UF = "PB"
    Case "59" VB_UF = "RN"
    Case "60" VB_UF = "CE"
    Case "61" VB_UF = "CE"
    Case "62" VB_UF = "CE"
    Case "63" VB_UF = "CE"
    Case "64" VB_UF = "PI"
    Case "65" VB_UF = "MA"
    Case "66" VB_UF = "PA"
    Case "67" VB_UF = "PA"
    Case "68" VB_UF = "PA"
              VB_UF2 = "AP"
    Case "69" VB_UF = "AM" 
              VB_UF2 = "AC" 
              VB_UF3 = "RR"
    Case "70" VB_UF = "DF"
    Case "71" VB_UF = "DF"
    Case "72" VB_UF = "DF" 
              VB_UF2 = "GO"
    Case "73" VB_UF = "DF" 
              VB_UF2 = "GO"
    Case "74" VB_UF = "GO"
    Case "75" VB_UF = "GO"
    Case "76" VB_UF = "GO"
    Case "77" VB_UF = "TO"
    Case "78" VB_UF = "MT" 
              VB_UF2 = "RO"
    Case "79" VB_UF = "MS"
    Case "80" VB_UF = "PR"
    Case "81" VB_UF = "PR"
    Case "82" VB_UF = "PR"
    Case "83" VB_UF = "PR"
    Case "84" VB_UF = "PR"
    Case "85" VB_UF = "PR"
    Case "86" VB_UF = "PR"
    Case "87" VB_UF = "PR"
    Case "88" VB_UF = "SC"
    Case "89" VB_UF = "SC"
    Case "90" VB_UF = "RS"
    Case "91" VB_UF = "RS"
    Case "92" VB_UF = "RS"
    Case "93" VB_UF = "RS"
    Case "94" VB_UF = "RS"
    Case "95" VB_UF = "RS"
    Case "96" VB_UF = "RS"
    Case "97" VB_UF = "RS"
    Case "98" VB_UF = "RS"
    Case "99" VB_UF = "GENERICA"
  End select
  'alert VB_UF
  'alert VB_UF2
  'alert VB_UF3

  if estadovalida = VB_UF or estadovalida = VB_UF2 or estadovalida = VB_UF3 then
    'msgbox "O CEP " & CepConsulta & " pertence ao estado " & estadovalida,64,"Informação"
    estadocep = TRUE
  else
    msgbox "O CEP " & CepConsulta & " não pertence ao estado " & estadovalida,48,"Informação"
    exit function
  end if
End function